# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal9611-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a51 m21 m31 m31s f41,$(TARGET_DEVICE)),)

endif
